service: healthconnect-websocket-disconnect

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 30
  memorySize: 256
  
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    WEBSOCKET_CONNECTIONS_TABLE: healthconnect-websocket-${self:provider.stage}-connections
    EVENT_BUS_NAME: healthconnect-websocket-${self:provider.stage}-event-bus
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.WEBSOCKET_CONNECTIONS_TABLE}
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - arn:aws:events:${self:provider.region}:${aws:accountId}:event-bus/${self:provider.environment.EVENT_BUS_NAME}
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  disconnect:
    handler: handler.lambda_handler
    description: Handle WebSocket disconnection events

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
