version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=healthconnect_user
      - DB_PASSWORD=healthconnect_pass
      - DB_NAME=healthconnect_dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=healthconnect_user
      - POSTGRES_PASSWORD=healthconnect_pass
      - POSTGRES_DB=healthconnect_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
