service: healthconnect-websocket-message

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 30
  memorySize: 512
  
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    WEBSOCKET_CONNECTIONS_TABLE: healthconnect-websocket-${self:provider.stage}-connections
    WEBSOCKET_MESSAGES_TABLE: healthconnect-websocket-${self:provider.stage}-messages
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.WEBSOCKET_CONNECTIONS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.WEBSOCKET_MESSAGES_TABLE}
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - arn:aws:execute-api:${self:provider.region}:${aws:accountId}:*/*/*/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  message:
    handler: handler.lambda_handler
    description: Handle WebSocket message routing and delivery

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
