AWSTemplateFormatVersion: '2010-09-09'
Description: 'HealthConnect AI - DynamoDB Tables Stack'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]

Resources:
  # KMS Key for DynamoDB Encryption
  DynamoDBKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for DynamoDB tables encryption - ${Environment}'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow DynamoDB Service
            Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'

  DynamoDBKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-dynamodb-${Environment}'
      TargetKeyId: !Ref DynamoDBKMSKey

  # Health Records Table
  HealthRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-health-records-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: data_type
          AttributeType: S
        - AttributeName: provider_id
          AttributeType: S
      KeySchema:
        - AttributeName: patient_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: DataTypeIndex
          KeySchema:
            - AttributeName: data_type
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ProviderIndex
          KeySchema:
            - AttributeName: provider_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref DynamoDBKMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: HealthRecords

  # Device Registry Table
  DeviceRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-device-registry-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: device_type
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PatientIndex
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
            - AttributeName: device_type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: DeviceTypeIndex
          KeySchema:
            - AttributeName: device_type
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref DynamoDBKMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: DeviceRegistry

  # Device Data Table
  DeviceDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-device-data-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: PatientIndex
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref DynamoDBKMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: DeviceData

  # Emergency Alerts Table
  EmergencyAlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-emergency-alerts-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: alert_id
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: urgency_level
          AttributeType: S
      KeySchema:
        - AttributeName: alert_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PatientIndex
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UrgencyIndex
          KeySchema:
            - AttributeName: urgency_level
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref DynamoDBKMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: EmergencyAlerts

  # Consultation Sessions Table
  ConsultationSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-consultation-sessions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: provider_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PatientIndex
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ProviderIndex
          KeySchema:
            - AttributeName: provider_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref DynamoDBKMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: ConsultationSessions

  # Analytics Results Table
  AnalyticsResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-analytics-results-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: analytics_run_id
          AttributeType: S
        - AttributeName: analytics_type
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: analytics_run_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TypeIndex
          KeySchema:
            - AttributeName: analytics_type
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref DynamoDBKMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: AnalyticsResults

Outputs:
  HealthRecordsTableName:
    Description: Health Records Table Name
    Value: !Ref HealthRecordsTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-HealthRecordsTable'

  DeviceRegistryTableName:
    Description: Device Registry Table Name
    Value: !Ref DeviceRegistryTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DeviceRegistryTable'

  DeviceDataTableName:
    Description: Device Data Table Name
    Value: !Ref DeviceDataTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DeviceDataTable'

  EmergencyAlertsTableName:
    Description: Emergency Alerts Table Name
    Value: !Ref EmergencyAlertsTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-EmergencyAlertsTable'

  ConsultationSessionsTableName:
    Description: Consultation Sessions Table Name
    Value: !Ref ConsultationSessionsTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ConsultationSessionsTable'

  AnalyticsResultsTableName:
    Description: Analytics Results Table Name
    Value: !Ref AnalyticsResultsTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-AnalyticsResultsTable'

  TableNames:
    Description: Comma-separated list of all table names
    Value: !Sub '${HealthRecordsTable},${DeviceRegistryTable},${DeviceDataTable},${EmergencyAlertsTable},${ConsultationSessionsTable},${AnalyticsResultsTable}'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-TableNames'

  DynamoDBKMSKeyId:
    Description: DynamoDB KMS Key ID
    Value: !Ref DynamoDBKMSKey
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DynamoDBKMSKey'
